name: Test Package Publishing
on: [push]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to the npm registry
        uses: "primer/publish@68a155f70e5eb9517b0ab3b7ecbcadbbdea90fc9"
        with:
          npm-args: "--unsafe-perm --allow-same-version"
          release-branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
