name: Test Package Publishing
on: [push]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to the npm registry
        uses: "primer/publish@800849649c6426c27773887b2cb50625a61f8ace"
        with:
          npm_args: "--unsafe-perm --allow-same-version"
          release_branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
