name: Test Package Publishing
on: [push]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
      - uses: actions/checkout@v1
      - name: Publish to the npm registry
        uses: "primer/publish@15a195dbb9b82116795a3325944a22223d00f8f5"
        with:
          release-branch: "main"
          npm-args: "--unsafe-perm --allow-same-version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
